export enum QueueJobType {
  AddVoters = "addVoters",
  AddElection = "addElection",
  ValidateElectionVotesDate = "validateElectionVotesDate",
  ValidateElectionVotesCount = "validateElectionVotesCount",
  ValidateOneVote = "checkUniqueVote",
  ValidateRepeatedVote = "checkRepeatedVote",
  AddVote = "addVote",
  GetElectionsInfo = "getElectionsInfo",
  ValidateVoterElectionCircuit = "voterElectionCircuit",
  GetVoter = "getVoter",
  GetVoteDates = "getVoteDates",
  GetVote = "getVote",
  GetVoteFrequency = "getVoteFrequency",
  GetTotalVotes = "getTotalVotes",
  GetCandidatesResult = "getCandidatesResult",
  GetPartiesResult = "getPartiesResult",
  GetElectionInfoCountPerCircuit = "getElectionInfoCountPerCircuit",
  GetElectionInfoCountPerState = "getElectionInfoCountPerState",
  GetElectionInfo = "getElectionInfo",
}
