export enum QueueJobPriority {
  AddVoters = 1,
  GetVote = 1,
  AddElection = 2,
  ValidateElectionVotesDate = 2,
  ValidateElectionVotesCount = 3,
  AddVote = 3,
  GetElectionsInfo = 4,
  ValidateOneVote = 5,
  ValidateRepeatedVote = 5,
  ValidateVoterElectionCircuit = 5,
  GetElectionInfoCountPerCircuit = 5,
  GetElectionInfoCountPerState = 5,
  GetVoter = 6,
  GetVoteDates = 6,
  GetVoteFrequency = 6,
  GetTotalVotes = 4,
  GetPartiesResult = 6,
  GetCandidatesResult = 6,
  GetElectionInfo = 10,
}
