export enum QueueJobPriority {
  AddVoters = 1,
  AddElection = 2,
  AddVote = 3,
  GetElectionsInfo = 4,
  ValidateOneVote = 5,
  ValidateRepeatedVote = 5,
  ValidateVoterElectionCircuit = 5,
  GetVoter = 6,
  GetVoteDates = 6,
  GetVote = 1,
  GetVoteFrequency = 6,
  GetTotalVotes = 4,
  GetCandidateResult = 6,
  GetPartyResult = 6,
}
